services:
  # Backend FastAPI service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        USE_S3_DATA: "false"  # Disable S3 data in local development
        AUTO_UPLOAD_DATA: "false"
    container_name: backend-local
    volumes:
      - ./data:/app/data  # Mount the data directory for persistent storage
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - CHROMA_DB_PATH=/app/data/chroma  # Set ChromaDB path inside the container
      - ENV=development  # Set environment to development
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8000:8000"  # Expose the FastAPI port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend React service
  frontend:
    build: ./frontend
    container_name: frontend-local
    restart: unless-stopped
    ports:
      - "3000:80"  # Expose the frontend on port 3000, served by Nginx on port 80 inside the container
    environment:
      - REACT_APP_API_URL=http://backend-local:8000  # Connect to the backend service
    depends_on:
      backend:
        condition: service_healthy  # Wait for backend to be healthy before starting
    networks:
      - app-network

# Shared network for service communication
networks:
  app-network:
    driver: bridge 