services:
  # Backend FastAPI service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./data:/app/data  # Mount the data directory for persistent storage
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - CHROMA_DB_PATH=/app/data/chroma  # Set ChromaDB path inside the container
      - ENV=production  # Set environment to production
      - AWS_REGION=${AWS_REGION:-us-east-2}  # Use AWS_REGION from .env or default to us-east-2
      - S3_DATA_BUCKET=${S3_DATA_BUCKET:-your-app-data-bucket}  # S3 bucket for data storage
      - USE_S3_DATA=${USE_S3_DATA:-false}  # Whether to use S3 for data (default: false for local dev)
      - AUTO_UPLOAD_DATA=${AUTO_UPLOAD_DATA:-false}  # Whether to automatically upload generated data
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8000:8000"  # Expose the FastAPI port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend React service
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"  # Expose the frontend on port 3000, served by Nginx on port 80 inside the container
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Connect to the backend service
    depends_on:
      backend:
        condition: service_healthy  # Wait for backend to be healthy before starting
    networks:
      - app-network

# Shared network for service communication
networks:
  app-network:
    driver: bridge 